apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: treetracker-wallet-api-v2
spec:
  cors:
    origins: 'https://prod-wallet-admin.treetracker.org'
    methods: GET, POST, PATCH, OPTIONS
    headers:
      - content-type
      - authorization
      - treetracker-api-key
