---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: treetracker-wallet-action-token
  namespace: wallet-api
spec:
  encryptedData:
    secret: AgAll8C0+dHYbNcLJC6jObS92rfXfFiYhxJ/V+nVPhZQXct30nNax2nrnNN6OnbaQwsCSvSfh465gL+ZBTkj8B9z7aF+t6xBLm89vuX1a5G1V/SeiW+ZKBg9F8jRQIZ6+84GcmAX8CL7v9wH2nEutq5sM+DIkl3WU4/1OylYMjhk5GV7Ld8fstOX/IiVzSeKG/yMQ7ePJ7zJddSuERKRCS5Y8m1z1LvvDULXtqoR5FK8nuFq+0gz6tsPtvFoy8Pwu7Yi5H8U5BX01vn8c1MEO/L2lu+YqtmkSJRLsZPsVkzNwIe8bC7Wg+1GcVjGETYAmpy0JRRH9F/eFjf0F3rgZjUv/shYK8LuLkq8FLtGVgklT42CHzoqa+acmbIik4CIq9qsTSM+qEk1ZgBiOuY5vFQ44ve0q+4MpI7OQb1qssSkElMjDMYFuSJn28jwIjOV3f4i1OAZofQVS1dgXx0o4WqhsEa0FwMHTi6MlHf4QEedBrTBU9MYaAFUC7hEfoHLP5bGNIGsyhiTpVlqI2UvfToYdR9AAbZjEpxnsf+dOSoeMLHJLYbPrz9ccV7VroEFpegbtqUc68ObTWSbiwU+XyiHnEuxiahg807dGas8vL1KBrwbhvKTGrI/5zIC2nz2UBZqc2pZ8plwLmOGdW4dHI8ROTkfwTQFqciUCKPz9q1YAkDxUdtF8C9P8DgUsKu4bsvt7Js8xohJO0KX7z0ohUBvC7E/m0NAMX822Igqg/WcLf3/1HCJTc+aV2+U3hhL/EnbmbSMC2ZOy2g80JKTGWuc
  template:
    metadata:
      name: treetracker-wallet-action-token
      namespace: wallet-api
