version: '3.1'

services:
  db:
    image: postgres:9-alpine
    restart: always
    environment:
      - POSTGRES_USER=wallet_user
      - POSTGRES_PASSWORD=secret
    ports:
      - '5432:5432'
    volumes:
      - postgres_volume:/var/lib/postgresql

  app:
    build: .
    restart: always
    environment:
      - DATABASE_URL=postgresql://wallet_user:secret@db:5432/wallet_user
      - DATABASE_SCHEMA=wallet
      - NODE_ENV=development
    ports:
      - '3006:3006'
    depends_on:
      - db

volumes:
  postgres_volume: {}
