version: '3.1'

services: 
  db: 
    image: postgres:9-alpine
    restart: always
    environment:
      - POSTGRES_USER=wallet_user
      - POSTGRES_PASSWORD=secret
    ports: 
      - 5432:5432
    volumes: 
      - postgres_volume:/var/lib/postgresql


volumes:
  postgres_volume: {}