FROM node:12.19.0-alpine
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
COPY package-lock.json ./
RUN npm ci --silent
COPY . ./

CMD cp database.json.ci database/database.json && \
    cd database && \
    sed -i "s#\[conn_str\]#${DATABASEURL}#g" database.json && \
     ../node_modules/db-migrate/bin/db-migrate --env dev up && \
    cd .. && \
    DATABASE_URL=${DATABASEURL} node .
