---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: treetracker-wallet-action-token
  namespace: wallet-api
spec:
  encryptedData:
    secret: AgCqYbrw4o8096qdFiaWzGmuOsBJ6Q4sGyFPKbCVg6I7IPbubVUxC+WH484dx8FlMoRiMBCaWpcpi7hMH/nMqnm8FP0/9yjSDYXcL7shgOPO/wCVwrqIgUeDDqihbrlKsPGeyUh3iXCs4P5ZzNSI+gr9LIy9lfrgQ/9ulPr/HdXpQfLOje+16QWwnsZbtG3gp8qezaij5U2r6Dq5ehTwHE0uDSh/HEvwbcrfO1KFw60IORxh+jxTSQbJ7b7Tq38NPZ9itxxZDRgObzGvjxz4PULa9O7h5VFCzNkUyhe9OPSnroulVV9zsDU/5WFMxIS5IL/rwawn3ZscUM596J8SISSeb4KnDIMVSjI9FrEqwK+npyp/zq1s0AzqizYQ0rOoZY/QF35D5mH2bH7Ve5WeDF8BCoMfjsYtpb197p4TKGC1qp8cHMyaI2oPf8nQMamOYJAyFHwEo1E1N7uRvigWwsykaeCxh/QX2IIv9GYq7kHHutmRgv3oOs2b5ilJnnbb8fsH1jSyoCsdENWqij0SBaENQA0U8/k72l1SHJ7oAxksqvUFX8qoThpZSRaptxuyrco6oAwi/NTyi+tei9f0ZqSaR+9T/4UXyYe0Eh4ChiL5fpGAJccmngvpQr+5blzglSV43m9vHrkYVSyCRWPYFIBilu9l5BPJ8sHxIpPcZxdJctiSoATiJDj1/mu31Y5xSKrCcEzhwm9VWCC8mk2rUHl4yfu9vT6zOYRjYEpXAxFa7aIHyuGzxcagS15FF4BgwWnepLcjogCIFdsOyMw85uTY
  template:
    metadata:
      name: treetracker-wallet-action-token
      namespace: wallet-api
