apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-wait-for
subjects:
  - kind: ServiceAccount
    name: default
    namespace: wallet-api
roleRef:
  kind: ClusterRole
  name: k8s-wait-for
  apiGroup: rbac.authorization.k8s.io
