apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-wait-for
rules:
  - apiGroups: ['']
    resources: ['services', 'pods', 'jobs']
    verbs: ['get', 'watch', 'list']
  - apiGroups: ['batch']
    resources: ['services', 'pods', 'jobs']
    verbs: ['get', 'watch', 'list']
