apiVersion: batch/v1
kind: Job
metadata:
  name: wallet-db-migration-job
spec:
  backoffLimit: 1 # allow for one re-try of the migration
  template:
    spec:
      containers:
        - name: migration
          image: greenstand/treetracker-wallet-api:TAG
          env:
            - name: BASE_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: treetracker-api-database-connection
                  key: db
            - name: DATABASE_URL
              value: '$(BASE_DATABASE_URL)&schema=wallet'
          command: ['node']
          args:
            [
              'node_modules/db-migrate/bin/db-migrate',
              'up',
              '--migrations-dir',
              'database/migrations/',
              '-v',
            ]
      restartPolicy: Never
