apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-wait-for-beta
subjects:
  - kind: ServiceAccount
    name: default
    namespace: wallet-api-beta
roleRef:
  kind: ClusterRole
  name: k8s-wait-for
  apiGroup: rbac.authorization.k8s.io
