#!/bin/zsh
API_ACCESS="-H \"TREETRACKER-API-KEY: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCEUrTBpq4zAoCLbwyOJtQW1K3bt9Ic66GkAzsRIGRxPTHOkKGC\""
export API_ACCESS
#echo $API_ACCESS
CONTENT_TYPE="-H \"Content-Type: application/json\""
export CONTENT_TYPE
HEADERS="${API_ACCESS} ${CONTENT_TYPE}"
export HEADERS
#echo $HEADERS

BEARER="-H \"Authorization: Bearer ${WALLET_BEARER_TOKEN}\""
export BEARER

#BASE_URL="http://localhost:8080"
#export BASE_URL
