name: Deploy to Beta Test Env

on:
  workflow_dispatch:
    inputs:
      git-tag:
        description: 'Git tag/branch/hash to deploy (e.g., v1.43.0-beta.2)'
        required: true
        default: 'beta'

env:
  project-directory: ./

jobs:
  deploy-beta-test:
    name: Deploy latest to beta test environment
    runs-on: ubuntu-latest
    if: github.repository == 'Greenstand/treetracker-wallet-api'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.git-tag }}


      - name: Get NPM Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        with:
          path: ./


      - name: Install kustomize
        run: curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash



      - name: Patch image tag in beta-test overlay
        # add code for local test
        # if: ${{ !env.ACT }}
        run: (cd deployment/overlays/beta/beta-test && ../../../../kustomize edit set image greenstand/treetracker-wallet-api:${{ steps.package-version.outputs.current-version }} )

      # - name: Patch image tag in beta-test overlay
      #   run: |
      #     cd /github/workspace/deployment/overlays/beta/beta-test
      #     /github/workspace/kustomize edit set image ronghu/treetracker-wallet-api:${{ steps.package-version.outputs.current-version }}

      
      ## comment out code for local testing
      # - name: Install doctl for kubernetes
      #   uses: digitalocean/action-doctl@v2
      #   with:
      #     token: ${{ secrets.TEST_DIGITALOCEAN_TOKEN }}

      # - name: Save DigitalOcean kubeconfig
      #   run: doctl kubernetes cluster kubeconfig save ${{ secrets.TEST_CLUSTER_NAME }}


      - name: Delete completed DB migration jobs
        # add code for local test
        if: ${{ !env.ACT }}
        run: kubectl -n wallet-api-beta delete job --ignore-not-found=true wallet-db-migration-job


      - name: Apply beta-test Kustomize overlay
        # add code for local test
        if: ${{ !env.ACT }}
        run: kustomize build deployment/overlays/beta/beta-test | kubectl apply -n ${{ secrets.K8S_NAMESPACE_BETA }} --wait -f -
