name: Deploy to Beta Test Env

on:
  workflow_dispatch:
    inputs:
      git-tag:
        description: 'Branch/hash/tag'
        required: true
        default: 'beta'

env:
  project-directory: ./

jobs:
  deploy-beta-test:
    name: Deploy latest to beta test environment, requires approval
    runs-on: ubuntu-latest
    if: github.repository == 'Greenstand/treetracker-wallet-api'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.git-tag }}

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        with:
          path: ./

      - name: Install kustomize
        run: curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash

      - name: Run kustomize
        run: (cd deployment/overlays/beta/beta-test && ../../../../kustomize edit set image greenstand/treetracker-wallet-api:${{ steps.package-version.outputs.current-version }} )

      - name: Install doctl for kubernetes
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.TEST_DIGITALOCEAN_TOKEN }}

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save ${{ secrets.TEST_CLUSTER_NAME }}

      - name: Delete completed migration jobs prior to deployment
        run: kubectl -n wallet-api-beta delete job wallet-db-migration-job

      - name: Update kubernetes resources
        run: kustomize build deployment/overlays/beta/beta-test | kubectl apply -n ${{ secrets.K8S_NAMESPACE_BETA }} --wait -f -
