# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Wallet API CI for New Pull Requests

on:
  pull_request:
    branches:
      - master
      - 'v1.10'

env:
  project-directory: ./

jobs:
  build:
    name: Run all tests
    runs-on: ubuntu-latest
    container: node:20.16.0-alpine3.20

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: npm clean install
        run: npm ci
        working-directory: ${{ env.project-directory }}

      - name: run ESLint
        run: npm run lint
        working-directory: ${{ env.project-directory }}

      - name: run db-migrate
        run: npm run db-migrate-ci
        working-directory: ${{ env.project-directory }}
        env:
          DATABASE_URL: postgresql://postgres:postgres@postgres/postgres

      - name: run test
        run: npm run test
        working-directory: ${{ env.project-directory }}
        env:
          DATABASE_URL: postgresql://postgres:postgres@postgres/postgres
          CI: true
